name: cloud-server-dev
services:
  cloud-server:
    build:
      context: .
      target: dev
    container_name: cloud-server-dev
    stdin_open: true
    ports:
      - "8082:8080"
    volumes:
      - .:/cloud_server:rw
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              # device_ids: ['1']
              capabilities: [gpu]
