[project]
name = "opencv-face"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.14"
dependencies = [
    "deepface>=0.0.96",
    "numpy>=2.2.6",
    "opencv-python>=4.12.0.88",
    "tf-keras>=2.20.1",
]
